# Generated by Django 6.0.1 on 2026-02-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_email_verification_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationotp',
            new_name='accounts_em_user_id_7155fd_idx',
            old_name='accounts_ema_user_id_2e6f47_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_user_id_6989e4_idx',
            old_name='accounts_ema_user_id_388073_idx',
        ),
    ]
