# Generated by Django 6.0.1 on 2026-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_accounts_ema_user_id_2e6f47_idx_accounts_em_user_id_7155fd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_photos/'),
        ),
    ]
