# Generated by Django 6.0.1 on 2026-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('hip-hop-rap', 'Hip-Hop / Rap'), ('pop', 'Pop'), ('folk-dohori', 'Folk / Dohori'), ('jazz', 'Jazz'), ('edm', 'EDM'), ('acoustic', 'Acoustic')], max_length=32, null=True),
        ),
    ]
