# Generated by Django 6.0.1 on 2026-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_concert_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='genre',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('hip-hop-rap', 'Hip-Hop / Rap'), ('pop', 'Pop'), ('folk-dohori', 'Folk / Dohori')], max_length=32, null=True),
        ),
    ]
