# Generated by Django 6.0.1 on 2026-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_concert_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
