# Generated by Django 6.0.1 on 2026-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=100),
        ),
    ]
