# Generated by Django 6.0.1 on 2026-02-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_ticketcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
