# Generated by Django 6.0.1 on 2026-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_ticketcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
