# Generated by Django 6.0.1 on 2026-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concert_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='concerts/covers/'),
        ),
    ]
